version: "3.8"

services:
  backend:
    build: ./backend
    container_name: spring-app
    ports:
      - "8080:8080"
    restart: always

  frontend:
    build: ./frontend
    container_name: frontend-app
    ports:
      - "5173:80"
    depends_on:
      - backend
    restart: always
